In [1]:
import numpy as np

In [2]:
#buat matrix X berukuran 2x3 menggunakan numpy
X = np.array([[45, 45], [45, 45], [45, 45]])
X

array([[45, 45],
       [45, 45],
       [45, 45]])

In [3]:
#tampilkan ukuran dari matrix X
X.shape

(3, 2)

In [4]:
X.size

6

In [5]:
#tampilkan seluruh elemen dari kolom pertama dari matrix X
X[:,0]

array([45, 45, 45])

In [6]:
#tampilkan seluruh elemen dari baris kedua dari matrix X
X[0,:]

array([45, 45])

ulangi soal nomor 1 menggunakan pytorch

In [7]:
import torch

In [8]:
#buat matrix X_pt berukuran 2x3 menggunakan pytorch
X_pt = torch.tensor([[45, 45], [45, 45], [45, 45]])
X_pt

tensor([[45, 45],
        [45, 45],
        [45, 45]])

In [9]:
#tampilkan ukuran dari matrix X_pt
X_pt.shape

torch.Size([3, 2])

In [10]:
#tampilkan seluruh elemen dari kolom pertama dari matrix X_pt
X_pt[:,0]

tensor([45, 45, 45])

In [11]:
#tampilkan seluruh elemen dari baris kedua dari matrix X
X_pt[0,:]

tensor([45, 45])

ulangi soal nomor 1 menggunakan tensorflow

In [12]:
import tensorflow as tf

In [13]:
#buat matrix X_tf berukuran 2x3 menggunakan tensorflow
X_tf = tf.Variable([[45, 45], [45, 45], [45, 45]])
X_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[45, 45],
       [45, 45],
       [45, 45]], dtype=int32)>

In [14]:
#tampilkan ukuran dari matrix X_tf
tf.shape(X_tf)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 2], dtype=int32)>

In [15]:
#tampilkan seluruh elemen dari kolom pertama dari matrix X_tf
X_tf[:,0]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([45, 45, 45], dtype=int32)>

In [16]:
#tampilkan seluruh elemen dari baris kedua dari matrix X_tf
X_tf[0,:]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([45, 45], dtype=int32)>