In [1]:
import numpy as np

In [2]:
#buat vector x dengan ukuran 3x1
x = np.array([45, 45, 45])
x

array([45, 45, 45])

In [3]:
#hitung panjang vector x
len(x)

3

In [4]:
#tampilkan ukuran vector x
x.shape

(3,)

In [5]:
#tampilkan tipe data dari vector x
type(x)

numpy.ndarray

In [6]:
#akses elemen pertama dari vector x
x[0]

np.int64(45)

In [7]:
#tampilkan tipe data elemen pertama dari vector x
type(x[0])

numpy.int64

In [8]:
#2 lakukan transpose pada vector x dan simpan pada variabel x_t
x_t = x.T
x_t

array([45, 45, 45])

In [9]:
#tampilkan ukuran dari vector x_t
x_t.shape

(3,)

In [10]:
#lakukan transpose pada vector y dan simpan pada variabel y_t
y = np.array([[45, 45, 45]])
y
y_t = y.T
y_t

array([[45],
       [45],
       [45]])

In [11]:
#tampilkan ukuran dari vector y_t
y_t.shape

(3, 1)

lakukan soal nomor 2 menggunakan pytorch dan tensorflow


In [12]:
import torch
import tensorflow as tf

In [13]:
#buat vector x dengan ukuran 3x1
x_pt = torch.tensor([45, 45, 5])
x_pt

tensor([45, 45, 45])

In [14]:
#hitung panjang vector x
len(x_pt)

3

In [15]:
#tampilkan ukuran vector x
x_pt.shape

torch.Size([3])

In [16]:
#tampilkan tipe data dari vector x
type(x_pt)

torch.Tensor

In [17]:
#akses elemen pertama dari vector x
x_pt[0]

tensor(45)

In [18]:
#lakukan transpose pada vector x dan simpan pada variabel x_t
x_pt_t = x_pt
x_pt_t

tensor([45, 45, 45])

In [19]:
#tampilkan ukuran dari vector x_t
x_pt_t.shape

torch.Size([3])

In [31]:
#lakukan transpose pada vector y dan simpan pada variabel y_t
y_pt = torch.tensor([[45, 45, 45]])
y_pt
y_pt_t = y_pt.T
y_pt_t

tensor([[45],
        [45],
        [45]])

In [32]:
#tampilkan ukuran dari vector y_t
y_pt_t.shape

torch.Size([3, 1])

TENSORFLOW

In [22]:
#buat vector x dengan ukuran 3x1
x_tf = tf.Variable([45, 45, 45])
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([45, 45, 45], dtype=int32)>

In [23]:
#tampilkan ukuran vector x
x_tf.shape

TensorShape([3])

In [24]:
#tampilkan tipe data dari vector x
x_tf.dtype

tf.int32

In [25]:
#akses elemen pertama dari vector x
x_tf[0]

<tf.Tensor: shape=(), dtype=int32, numpy=45>

In [26]:
#lakukan transpose pada vector x dan simpan pada variabel x_t
x_tf_t = x_tf
x_tf_t

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([45, 45, 45], dtype=int32)>

In [27]:
#tampilkan ukuran dari vector x_t
x_tf_t.shape

TensorShape([3])

In [29]:
#lakukan transpose pada vector y dan simpan pada variabel y_t
y_tf = tf.Variable([[45, 45, 45]])
y_tf
y_tf_t = tf.transpose(y_tf)
y_tf_t

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[45],
       [45],
       [45]], dtype=int32)>

In [30]:
#tampilkan ukuran dari vector y_t
y_tf_t.shape

TensorShape([3, 1])