SOAL SUB BAB 1

In [1]:
import numpy as np
import torch
import tensorflow as tf

In [2]:
# Buat matrix X (2x3) dengan NumPy
X = np.array([[1, 2, 3],
              [4, 5, 6]])
X

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# Buat matrix X_pt (2x3) dengan PyTorch
X_pt = torch.tensor([[1, 2, 3],
                     [4, 5, 6]], dtype=torch.float32)
X_pt

In [3]:
# Buat matrix X_tf (2x3) dengan TensorFlow
X_tf = tf.constant([[1, 2, 3],
                    [4, 5, 6]], dtype=tf.float32)
X_tf

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [15]:
scalar = 2

# Perkalian
mul_np = X * scalar
mul_pt = X_pt * scalar
mul_tf = X_tf * scalar
print (mul_np)
print (mul_pt)
print (mul_tf)

[[ 8 16 24]
 [32 40 48]]
tensor([[ 4.,  8., 12.],
        [16., 20., 24.]])
tf.Tensor(
[[ 4.  8. 12.]
 [16. 20. 24.]], shape=(2, 3), dtype=float32)


In [16]:
# Penjumlahan
add_np = X + scalar
add_pt = X_pt + scalar
add_tf = X_tf + scalar
print (add_np)
print (add_pt)
print (add_tf)

[[ 6 10 14]
 [18 22 26]]
tensor([[ 4.,  6.,  8.],
        [10., 12., 14.]])
tf.Tensor(
[[ 4.  6.  8.]
 [10. 12. 14.]], shape=(2, 3), dtype=float32)


In [17]:
# Pengurangan
sub_np = X - scalar
sub_pt = X_pt - scalar
sub_tf = X_tf - scalar
print (sub_np)
print (sub_pt)
print (sub_tf)

[[ 2  6 10]
 [14 18 22]]
tensor([[ 0.,  2.,  4.],
        [ 6.,  8., 10.]])
tf.Tensor(
[[ 0.  2.  4.]
 [ 6.  8. 10.]], shape=(2, 3), dtype=float32)


SOAL SUB BAB 2

In [21]:
# Buat matrix Y (2x3) dengan NumPy
Y = np.array([[1, 2, 3],
              [4, 5, 6]])
Y

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
# Buat matrix Y_pt (2x3) dengan PyTorch
Y_pt = torch.tensor([[1, 2, 3],
                     [4, 5, 6]], dtype=torch.float32)
Y_pt

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [23]:
# Buat matrix Y_tf (2x3) dengan TensorFlow
Y_tf = tf.constant([[1, 2, 3],
                    [4, 5, 6]], dtype=tf.float32)
Y_tf

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [29]:
# NumPy
res_np = X * Y

# PyTorch
res_pt = X_pt * Y_pt

# TensorFlow
res_tf = X_tf * Y_tf

print (res_np)
print (res_pt)
print (res_tf)

[[ 1  4  9]
 [16 25 36]]
tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])
tf.Tensor(
[[ 1.  4.  9.]
 [16. 25. 36.]], shape=(2, 3), dtype=float32)
