In [6]:
import numpy as np
import tensorflow as tf
import torch as pt

In [3]:
#buat matrix X dengan ukuran 2x3 menggunakan numpy
X = np.array([[45,45,45],[45,45,45]])

In [4]:
#hitung berapa hasil penjumlahan elemen matrix X dengan fungsi sum
X.sum()

np.int64(270)

In [7]:
#buat matrix X_tf dengan ukuran 2x3 menggunakan tensorflow
X_tf = tf.Variable([[45,45,45],[45,45,45]])

In [8]:
X_pt = pt.tensor([[45,45,45],[45,45,45]])

In [12]:
#hitung hasil penjumlahan seluruh elemen matrix X
X.sum()

np.int64(270)

In [10]:
#hitung hasil penjumlahan seluruh elemen matrix X_pt
pt.sum(X_pt)

tensor(270)

In [11]:
#hitung hasil penjumlahan seluruh elemen matrix X_tf
tf.reduce_sum(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=270>

In [16]:
#hitung hasil penjumlahan matrix X berdasarkan row nya
X.sum(axis=0)

array([90, 90, 90])

In [19]:
#hitung hasil penjumlahan matrix X_pt berdasarkan row nya
pt.sum(X_pt, axis = 0)

tensor([90, 90, 90])

In [20]:
#hitung hasil penjumlahan matrix X_tf berdasarkan row nya
tf.reduce_sum(X_tf, axis=0)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([90, 90, 90], dtype=int32)>

In [22]:
#hitung hasil penjumlahan matrix X berdasarkan kolom nya
X.sum(axis=1)

array([135, 135])

In [23]:
#hitung hasil penjumlahan matrix X_pt berdasarkan kolom nya
pt.sum(X_pt, axis = 1)

tensor([135, 135])

In [24]:
#hitung hasil penjumlahan matrix X_tf berdasarkan kolom nya
tf.reduce_sum(X_tf, axis=1)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([135, 135], dtype=int32)>

In [25]:
#"hitung nilai minimal dari matrix X, X_pt dan X_tf"
print(X.min())
print(pt.min(X_pt))
print(tf.reduce_min(X_tf))

45
tensor(45)
tf.Tensor(45, shape=(), dtype=int32)


In [26]:
#"hitung nilai maksimal dari matrix X, X_pt dan X_tf"
print(X.max())
print(pt.max(X_pt))
print(tf.reduce_max(X_tf))

45
tensor(45)
tf.Tensor(45, shape=(), dtype=int32)


In [33]:
#"hitung nilai rata-rata dari matrix X, X_pt dan X_tf"
print(X.mean())
print(pt.mean(X_pt.float()))
print(tf.reduce_mean(X_tf))

45.0
tensor(45.)
tf.Tensor(45, shape=(), dtype=int32)


In [42]:
#hitung hasil perkalian seluruh elemen matrix X
print(X.prod())
#hitung hasil perkalian seluruh elemen matrix X_pt
print(pt.prod(X_pt))
#hitung hasil perkalian seluruh elemen matrix X_tf
print(tf.reduce_prod(X_tf)) # akan terjadi overflow karna int yang digunakan hanya 32 byte
print(tf.reduce_prod(tf.cast(X_tf, dtype=tf.int64))) #saya ubah jadi 64

8303765625
tensor(8303765625)
tf.Tensor(-286168967, shape=(), dtype=int32)
tf.Tensor(8303765625, shape=(), dtype=int64)
