In [4]:
import numpy as np
import torch
import tensorflow as tf

SOAL 1 - Tensor Transposotion

In [6]:
# Buat matrix X (2x3) dengan NumPy
X = np.array([[1, 2, 3],
              [4, 5, 6]])
X

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
# Buat matrix X_pt (2x3) dengan PyTorch
X_pt = torch.tensor([[1, 2, 3],
                     [4, 5, 6]], dtype=torch.float32)
X_pt

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [10]:
# Buat matrix X_tf (2x3) dengan TensorFlow
X_tf = tf.constant([[1, 2, 3],
                    [4, 5, 6]], dtype=tf.float32)
X_tf

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [14]:
# 1. Transpose Matrix X (NumPy)
X_transposed = X.T

print("Transpose NumPy:")
print(X_transposed)

# 2. Transpose Matrix X_pt (PyTorch)
X_pt_transposed = X_pt.T

print("\nTranspose PyTorch:")
print(X_pt_transposed)

# 3. Transpose Matrix X_tf (TensorFlow)
X_tf_transposed = tf.transpose(X_tf)

print("\nTranspose TensorFlow:")
print(X_tf_transposed)

Transpose NumPy:
[[1 4]
 [2 5]
 [3 6]]

Transpose PyTorch:
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

Transpose TensorFlow:
tf.Tensor(
[[1. 4.]
 [2. 5.]
 [3. 6.]], shape=(3, 2), dtype=float32)
