In [ ]:
#1 buat vector x dan y dengan ukuran 1x3 menggunakan numpy

In [ ]:
import numpy as np

In [ ]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [ ]:
y = np.array([4,5,6])
y

array([[4, 5, 6]])

In [ ]:
#buat vector x_pt dan y_pt dengan ukuran 1x3 menggunakan pytorch

In [ ]:
import torch as pt

In [ ]:
x_pt = pt.tensor([1,2,3])
x_pt

tensor([1, 2, 3])

In [ ]:
y_pt = pt.tensor([4,5,6])
y_pt

tensor([4, 5, 6])

In [ ]:
#buat vector x_tf dan y_tf dengan ukuran 1x3 menggunakan tensorflow

In [ ]:
import tensorflow as tf

In [ ]:
x_tf = tf.Variable([1,2,3])
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [ ]:
y_tf = tf.Variable([4,5,6])
y_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([4, 5, 6], dtype=int32)>

In [ ]:
#2 hitung perkalian dot product antara vector x dan vector y

In [ ]:
1*4 + 2*5 + 3*6

32

In [ ]:
np.dot(x, y)

ValueError: shapes (3,) and (2,2) not aligned: 3 (dim 0) != 2 (dim 0)

In [ ]:
#hitung perkalian dot product antara vector x_pt dan vector y_pt

In [ ]:
pt.dot(x_pt, y_pt)

tensor(32)

In [ ]:
#hitung perkalian dot product antara vector x_tf dan vector y_tf

In [ ]:
tf.reduce_sum(tf.multiply(x_tf, y_tf))

<tf.Tensor: shape=(), dtype=int32, numpy=32>

In [ ]:
#3 lakukan perhitungan excercise menggunakan collab

In [ ]:
#what is y transpose?
y = np.array([[42,4,7,99],
              [-99,-3,17,22]
])
y_t = y.T
y_t

array([[ 42, -99],
       [  4,  -3],
       [  7,  17],
       [ 99,  22]])

In [ ]:
#what is the hadamasd product of these matrices?
a = np.array([[25,10],
              [-2,1]
])
b = np.array([[-1,7],
              [10,8]
])
(a*b)

array([[-25,  70],
       [-20,   8]])

In [ ]:
#what is the dot product of the tensor w and x?
w = np.array([-1,2,-2])
x = np.array([5,10,0])

np.dot(w, x)

np.int64(15)