In [1]:
#menggunakan numpy, pytoch dan tensorflow buatlah matrix ukuran 3x3 lalu hitung nilai frobenius norm
import numpy as np

In [2]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
(1**2 + 2**2 + 3**2 + 4**2 + 5**2 + 6**2 + 7**2 + 8**2+ 9**2)**(1/2)

16.881943016134134

In [5]:
np.linalg.norm(x)

np.float64(16.881943016134134)

In [6]:
import torch

In [14]:
x_pt = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9.]])
x_pt

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [15]:
torch.norm(x_pt)

tensor(16.8819)

In [16]:
import tensorflow as tf


In [17]:
x_tf = tf.Variable([[1, 2, 3], [4, 5, 6], [7, 8, 9.]])
x_tf

<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)>

In [19]:
tf.norm(x_tf)

<tf.Tensor: shape=(), dtype=float32, numpy=16.881942749023438>