In [1]:
import numpy as np

lakukan perhitungan soal excercise menggunakan collab

In [3]:
import torch
M_q = torch.tensor([[10, 10, 10], [10, 10, 10], [10, 10, 10]])
M_q

tensor([[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]])

In [4]:
V_q = torch.tensor([[10, 10, 10], [10, 10, 10]]).T
V_q

tensor([[10, 10],
        [10, 10],
        [10, 10]])

In [5]:
torch.matmul(M_q, V_q)

tensor([[300, 300],
        [300, 300],
        [300, 300]])