In [ ]:
#1. buat matrix A dengan ukuran 2x3 dan vector b berukuran 3x1 menggunakan numpy

In [1]:
import numpy as np

In [62]:
A = np.array([[3, 4, 5], [6, 7, 8]])
A

array([[3, 4, 5],
       [6, 7, 8]])

In [14]:
A.shape

(2, 3)

In [12]:
b = np.array([[1],[2],[3]])
b

array([[1],
       [2],
       [3]])

In [13]:
b.shape

(3, 1)

In [10]:
np.dot(A, b)

array([[26],
       [44]])

In [15]:
#buat matrix A_pt dengan ukuran 2x3 dan vector b_pt berukuran 3x1 menggunakan pytorch
import torch

In [47]:
A_pt = torch.tensor([[9, 10, 11], [12, 13, 14]])
A_pt

tensor([[ 9, 10, 11],
        [12, 13, 14]])

In [17]:
b_pt = torch.tensor([[11], [12], [13]])
b_pt

tensor([[11],
        [12],
        [13]])

In [18]:
#buat matrix A_tf dengan ukuran 2x3 dan vector b_tf berukuran 3x1 menggunakan tensorflow
import tensorflow as tf

In [23]:
A_tf = tf.Variable([[15, 16, 17], [18, 19, 20]])
A_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[15, 16, 17],
       [18, 19, 20]], dtype=int32)>

In [24]:
b_tf = tf.Variable([[14], [15], [16]])
b_tf

<tf.Variable 'Variable:0' shape=(3, 1) dtype=int32, numpy=
array([[14],
       [15],
       [16]], dtype=int32)>

In [34]:
#tampilkan ukuran matrix A dan vector b
print(A.shape)
print(b.shape)
print(A_pt.shape)
print(b_pt.shape)
print(A_tf.shape)
print(b_tf.shape)

torch.Size([2, 3])
(3, 1)
torch.Size([2, 3])
torch.Size([3, 1])
(2, 3)
(3, 1)


In [36]:
#kalikan matrix A dengan vector b
np.dot(A, b)

/tmp/ipykernel_2850/2157879621.py:2: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  np.dot(A, b)


array([[62],
       [80]])

In [37]:
#kalikan matrix A_pt dengan vector b_pt
torch.matmul(A_pt, b_pt)

tensor([[362],
        [470]])

In [44]:
#kalikan matrix A_tf dengan vector b_tf
tf.matmul(A_tf, b_tf)

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[722],
       [857]], dtype=int32)>

In [61]:
#buat matrix B dengan ukuran 3x3 menggunakan numpy
B = np.array([[3, 6, 5], [9, 1, 2], [8, 7, 2]])
B

array([[3, 6, 5],
       [9, 1, 2],
       [8, 7, 2]])

In [41]:
#buat matrix B_pt dengan ukuran 3x3 menggunakan pytorch
B_pt = torch.tensor([[9, 10, 11], [12, 13, 14], [3, 5, 8]])
B_pt

tensor([[ 9, 10, 11],
        [12, 13, 14],
        [ 3,  5,  8]])

In [48]:
#buat matrix B_tf dengan ukuran 3x3 menggunakan tensorflow
B_tf = tf.Variable([[2, 5, 0], [6, 1, 0], [8, 8, 4]])
B_tf

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[2, 5, 0],
       [6, 1, 0],
       [8, 8, 4]], dtype=int32)>

In [54]:
#kalikan matrix A dengan matrix B
np.dot(A, B)

/tmp/ipykernel_2850/1264322347.py:2: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  np.dot(A, B)


array([[205, 141,  87],
       [265, 183, 114]])

In [53]:
#kalikan matrix A_pt dengan matrix B_pt
torch.matmul(A_pt, b_pt)

tensor([[362],
        [470]])

In [52]:
#kalikan matrix A_tf dengan matrix B_tf
tf.matmul(A_tf, B_tf)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[262, 227,  68],
       [310, 269,  80]], dtype=int32)>

In [58]:
#buktikan apakah perkalian matrix bersifat komutatif? (AB=BA)?
np.dot(A, B)

/tmp/ipykernel_2850/498592208.py:2: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  np.dot(A, B)


array([[205, 141,  87],
       [265, 183, 114]])

In [63]:
np.dot(B, A)

ValueError: shapes (3,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [ ]:
#Jika di lihat A(2x3)*B(3x3) berhasil dan B(3x3)*A(2x3)tidak bisa karena kolom B dan baris A tidak sama sehingga muncul eror
#kesimpulan : Tidak Komutatif!