In [1]:
import numpy as np

In [2]:
#buatlah matriks simetris dengan ukuran 3x3 dan buktikan bahwa itu merupakan matriks simetris
X_sym = np.array([[10, 10, 10], [10, 10, 10], [10, 10, 10]])
X_sym

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [3]:
import torch

In [4]:
#menggunakan pytorch, buatlah matriks identitas I dengan ukuran 4x4
I = torch.eye(4)
I

Matriks I (4x4):
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


In [5]:
#menggunakan pytorch, buatlah vector b_pt dengan ukuran 4x1
b_pt = torch.tensor([[1.0],
                     [2.0],
                     [3.0],
                     [4.0]])
b_pt


Vektor b_pt (4x1):
tensor([[1.],
        [2.],
        [3.],
        [4.]])


In [6]:
#kalikan matrix I dengan vector b_pt
hasil_kali = torch.matmul(I, b_pt)
hasil_kali


Hasil perkalian I dengan b_pt:
tensor([[1.],
        [2.],
        [3.],
        [4.]])
